/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as CodeforcesToGithubRouteImport } from "./routes/codeforces-to-github";
import { Route as LeetcodeToGithubRouteImport } from "./routes/leetcode-to-github";
import { Route as PrivacyRouteImport } from "./routes/privacy";
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const CodeforcesToGithubRoute = CodeforcesToGithubRouteImport.update({
  id: "/codeforces-to-github",
  path: "/codeforces-to-github",
  getParentRoute: () => rootRouteImport,
});
const LeetcodeToGithubRoute = LeetcodeToGithubRouteImport.update({
  id: "/leetcode-to-github",
  path: "/leetcode-to-github",
  getParentRoute: () => rootRouteImport,
});
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeforcesToGithubRoute: CodeforcesToGithubRoute,
  LeetcodeToGithubRoute: LeetcodeToGithubRoute,
  PrivacyRoute: PrivacyRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
