/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeforcesToGithubRouteImport } from './routes/codeforces-to-github'
import { Route as LeetcodeToGithubRouteImport } from './routes/leetcode-to-github'
import { Route as PrivacyRouteImport } from './routes/privacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeforcesToGithubRoute = CodeforcesToGithubRouteImport.update({
  id: '/codeforces-to-github',
  path: '/codeforces-to-github',
  getParentRoute: () => rootRouteImport,
} as any)
const LeetcodeToGithubRoute = LeetcodeToGithubRouteImport.update({
  id: '/leetcode-to-github',
  path: '/leetcode-to-github',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codeforces-to-github': typeof CodeforcesToGithubRoute
  '/leetcode-to-github': typeof LeetcodeToGithubRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codeforces-to-github': typeof CodeforcesToGithubRoute
  '/leetcode-to-github': typeof LeetcodeToGithubRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codeforces-to-github': typeof CodeforcesToGithubRoute
  '/leetcode-to-github': typeof LeetcodeToGithubRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/codeforces-to-github' | '/leetcode-to-github' | '/privacy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/codeforces-to-github' | '/leetcode-to-github' | '/privacy'
  id:
    | '__root__'
    | '/'
    | '/codeforces-to-github'
    | '/leetcode-to-github'
    | '/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeforcesToGithubRoute: typeof CodeforcesToGithubRoute
  LeetcodeToGithubRoute: typeof LeetcodeToGithubRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codeforces-to-github': {
      id: '/codeforces-to-github'
      path: '/codeforces-to-github'
      fullPath: '/codeforces-to-github'
      preLoaderRoute: typeof CodeforcesToGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leetcode-to-github': {
      id: '/leetcode-to-github'
      path: '/leetcode-to-github'
      fullPath: '/leetcode-to-github'
      preLoaderRoute: typeof LeetcodeToGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeforcesToGithubRoute: CodeforcesToGithubRoute,
  LeetcodeToGithubRoute: LeetcodeToGithubRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
